Change arm build detection to use new waf 1.5 features
Instead of ARM9 and ARM7, now uses HOST and ARM7. This means SDL and NDS
build variants can be cloned directly. ARM9 is the equivalent to HOST really.

Cut the monolithic detect-like function into smaller methods attached to the
conf object. Create arm9 and arm7 uselib sets at the same time instead of
requiring 2 calls - saves detecting things twice.

* Update to waf 1.5 trunk
waf 1.5 improves tests on obj.source so the dummy.c files are no longer needed
In configure script, fix colours, fix lack of dirname on Windows git-mingw
Add a configuration summary when running "waf configure", clean up options
sox: Fix configuration width mess up

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -6,16 +6,12 @@
 #
 if [ "$NOCOLOR" ] ; then
     NORMAL=""
-    BOLD=""
     RED=""
-    YELLOW=""
     GREEN=""
 else
-    NORMAL="\033[0m"
-    BOLD="\033[1m"
-    RED="\033[91m"
-    YELLOW="\033[01;93m"
-    GREEN="\033[92m"
+    NORMAL="\x1b[0m"
+    RED="\x1b[01;91m"
+    GREEN="\x1b[32m"
 fi
 
 EXIT_SUCCESS=0
@@ -23,15 +19,16 @@ EXIT_FAILURE=1
 EXIT_ERROR=2
 EXIT_BUG=10
 
-CUR_DIR=$PWD
-
-#possible relative path
-WORKINGDIR=`dirname $0`
-cd $WORKINGDIR
-#abs path
-WORKINGDIR=`pwd`
-cd $CUR_DIR
-
+calculateWorkingDir()
+{
+	CUR_DIR=$PWD
+	#possible relative path
+	WORKINGDIR=$(python -c 'import os; print os.path.dirname("'$0'")')
+	cd $WORKINGDIR
+	#abs path
+	WORKINGDIR=`pwd`
+	cd $CUR_DIR
+}
 # Checks for Python interpreter. Honours $PYTHON if set. Stores path to
 # interpreter in $PYTHON.
 #
@@ -42,13 +39,13 @@ checkPython()
 	fi
 	printf "Checking for Python\t\t\t:  "
 	if [ ! -x "$PYTHON" ] ; then
-	  printf $RED"not found!"$NORMAL"\n"
+	  printf "${RED}not found!$NORMAL\n"
 	  echo "Please make sure that the Python interpreter is available in your PATH"
 	  echo "or invoke configure using the PYTHON flag, e.g."
 	  echo "$ PYTHON=/usr/local/bin/python configure"
 	  exit $EXIT_FAILURE
 	fi
-	printf $GREEN"$PYTHON"$NORMAL"\n"
+	printf "$GREEN$PYTHON$NORMAL\n"
 }
 
 # Checks for WAF. Honours $WAF if set. Stores path to 'waf' in $WAF.
@@ -72,18 +69,24 @@ checkWAF()
 	        WAF="${WORKINGDIR}/waf"
 	    fi
 	fi
+	if [ -z $WAF ] && [ -n $WAFDIR ] ; then
+		WORKINGDIR=$WAFDIR
+		if [ -f "${WORKINGDIR}/../waf-light" ] ; then
+			WAF="${WORKINGDIR}/../waf-light"
+		fi
+	fi
 	#global installed waf with waf->waf.py link
 	if [ -z "$WAF" ] ; then
 	    WAF=`which waf 2>/dev/null`
 	fi
 	# neither waf nor miniwaf could be found
 	if [ ! -x "$WAF" ] ; then
-	    printf $RED"not found"$NORMAL"\n"
+	    printf "${RED}not found$NORMAL\n"
 	    echo "Go to http://code.google.com/p/waf/"
 	    echo "and download a waf version"
 	    exit $EXIT_FAILURE
 	else
-	  printf $GREEN"$WAF"$NORMAL"\n"
+	  printf "$GREEN$WAF$NORMAL\n"
 	fi
 }
 
@@ -136,14 +139,11 @@ EOF
 }
 
 checkPython
+calculateWorkingDir
 checkWAF
 
-$WAF configure $* || exit $EXIT_ERROR
+$WAF configure $@ || exit $EXIT_ERROR
 
-if [ -f "Makefile" ] ; then
-    echo ""
-else
-    generateMakefile
-fi
+generateMakefile
 
 exit $EXIT_SUCCESS
